layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: lawrencereddy
  # mastodon: your_username
  medium: lawrencereddy
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: @lawrencereddy
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Writing
    web_url: https://medium.com/@lawrencereddy
    image_url: 

  - name: Editing

  - name: Reading
    web_url: 
    image_url: 
